services:
  dev:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    container_name: notes-dev
    env_file: ../../.env.local
    environment:
      - WATCHPACK_POLLING=true
      - HOSTNAME=0.0.0.0
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ../..
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: package.json
